module.exports = {
  'capitalized-comments': 'off',
  'class-methods-use-this': 'off',
  'dot-location': ['error', 'property'],
  indent: ['error', 2],
  'init-declarations': 'off',
  'newline-after-var': 'off',
  'no-console': 'off',
  'no-magic-numbers': 'off',
  'no-negated-condition': 'off',
  'no-process-env': 'off',
  'no-unused-vars': 'warn',
  'object-curly-newline': 'off',
  'object-curly-spacing': ['error', 'always'],
  'one-var': ['error', 'never'],
  'padded-blocks': ['error', 'never'],
  'quote-props': ['error', 'as-needed'],
  quotes: ['error', 'single'],
  radix: ['warn', 'as-needed'],
  semi: ['error', 'never'],
  'sort-imports': 'off',
  'sort-keys': 'off',
  'space-before-function-paren': ['error', 'never'],
  strict: 'off',
  'template-curly-spacing': ['error', 'always']
}
